-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agent_decisions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  agent_name text NOT NULL,
  step_name text NOT NULL,
  decision_type text NOT NULL CHECK (decision_type = ANY (ARRAY['classification'::text, 'extraction'::text, 'routing'::text, 'action'::text, 'escalation'::text, 'approval'::text])),
  input_summary text,
  output_summary text,
  confidence numeric,
  model_used text,
  tokens_input integer DEFAULT 0,
  tokens_output integer DEFAULT 0,
  latency_ms integer,
  escalated_to_human boolean DEFAULT false,
  human_override text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_decisions_pkey PRIMARY KEY (id),
  CONSTRAINT agent_decisions_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.agent_runs(id)
);
CREATE TABLE public.agent_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  agent_name text NOT NULL,
  total_runs integer DEFAULT 0,
  successful_runs integer DEFAULT 0,
  failed_runs integer DEFAULT 0,
  avg_duration_ms integer DEFAULT 0,
  p95_duration_ms integer DEFAULT 0,
  total_tokens integer DEFAULT 0,
  total_cost_usd numeric DEFAULT 0,
  cache_hit_rate numeric DEFAULT 0,
  escalation_rate numeric DEFAULT 0,
  avg_confidence numeric DEFAULT 0,
  top_decision_types jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.agent_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_name text NOT NULL CHECK (agent_name = ANY (ARRAY['captador'::text, 'operacional'::text, 'comunicador'::text, 'orquestrador'::text])),
  trigger_type text NOT NULL CHECK (trigger_type = ANY (ARRAY['cron'::text, 'webhook'::text, 'manual'::text, 'urgent'::text, 'chain'::text])),
  trigger_source text,
  company_id uuid,
  status text NOT NULL DEFAULT 'running'::text CHECK (status = ANY (ARRAY['running'::text, 'completed'::text, 'failed'::text, 'timeout'::text, 'cancelled'::text])),
  input_data jsonb DEFAULT '{}'::jsonb,
  output_data jsonb DEFAULT '{}'::jsonb,
  error_message text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  duration_ms integer,
  total_tokens_used integer DEFAULT 0,
  total_cost_usd numeric DEFAULT 0,
  cache_read_tokens integer DEFAULT 0,
  cache_write_tokens integer DEFAULT 0,
  steps_executed integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_runs_pkey PRIMARY KEY (id),
  CONSTRAINT agent_runs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  acao text NOT NULL,
  detalhes jsonb DEFAULT '{}'::jsonb,
  ip text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.billing_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  valor numeric NOT NULL,
  status text NOT NULL DEFAULT 'pendente'::text CHECK (status = ANY (ARRAY['pendente'::text, 'pago'::text, 'atrasado'::text, 'cancelado'::text])),
  asaas_payment_id text,
  metodo_pagamento text,
  data_vencimento date NOT NULL,
  data_pagamento timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT billing_history_pkey PRIMARY KEY (id),
  CONSTRAINT billing_history_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  cnpj text NOT NULL UNIQUE,
  razao_social text NOT NULL,
  nome_fantasia text,
  alvara_numero text,
  alvara_validade date,
  plano text NOT NULL DEFAULT 'starter'::text CHECK (plano = ANY (ARRAY['starter'::text, 'professional'::text, 'enterprise'::text, 'custom'::text])),
  valor_mensal numeric NOT NULL DEFAULT 497.00,
  billing_status text NOT NULL DEFAULT 'trial'::text CHECK (billing_status = ANY (ARRAY['trial'::text, 'ativo'::text, 'inadimplente'::text, 'suspenso'::text, 'cancelado'::text])),
  data_proxima_cobranca date,
  habilitada boolean NOT NULL DEFAULT false,
  email_operacional text NOT NULL,
  email_responsavel text NOT NULL,
  telefone text,
  uf_sede character NOT NULL,
  ecpf_r2_path text,
  ecpf_senha_encrypted text,
  ecpf_validade date,
  alertas_ativos jsonb NOT NULL DEFAULT '{"ecpf_validade": true, "alvara_validade": true}'::jsonb,
  asaas_customer_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  matriz_id uuid,
  tipo_unidade text NOT NULL DEFAULT 'matriz'::text CHECK (tipo_unidade = ANY (ARRAY['matriz'::text, 'filial'::text])),
  procuracao_status text DEFAULT 'nao_iniciada'::text CHECK (procuracao_status = ANY (ARRAY['nao_iniciada'::text, 'pendente'::text, 'validada'::text, 'rejeitada'::text, 'revogada'::text])),
  cnae_principal character varying,
  cnae_descricao text,
  capital_social numeric,
  porte text,
  data_abertura character varying,
  natureza_juridica text,
  logradouro text,
  numero character varying,
  complemento text,
  bairro text,
  cep character varying,
  municipio text,
  situacao_cadastral text,
  enriched_at timestamp with time zone,
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_matriz_id_fkey FOREIGN KEY (matriz_id) REFERENCES public.companies(id)
);
CREATE TABLE public.company_instructions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  titulo text NOT NULL,
  conteudo text NOT NULL,
  categoria text NOT NULL DEFAULT 'geral'::text CHECK (categoria = ANY (ARRAY['geral'::text, 'gesp'::text, 'monitoramento'::text, 'financeiro'::text, 'comunicacao'::text])),
  ativo boolean NOT NULL DEFAULT true,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT company_instructions_pkey PRIMARY KEY (id),
  CONSTRAINT company_instructions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT company_instructions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT company_instructions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.delesp_contacts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  uf character NOT NULL UNIQUE,
  estado text NOT NULL,
  email text NOT NULL,
  telefone text,
  observacoes text,
  ativo boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT delesp_contacts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.discrepancies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  employee_id uuid,
  gesp_task_id uuid,
  tipo_incompatibilidade text NOT NULL,
  campo_divergente text NOT NULL,
  valor_sistema text,
  valor_gesp text,
  print_documento_r2 text NOT NULL,
  print_gesp_r2 text NOT NULL,
  print_erro_r2 text,
  oficio_id uuid,
  delesp_uf character,
  status text NOT NULL DEFAULT 'aberta'::text CHECK (status = ANY (ARRAY['aberta'::text, 'comunicada'::text, 'resolvida'::text, 'arquivada'::text])),
  prazo_resposta_pf date,
  resolucao_detalhe text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT discrepancies_pkey PRIMARY KEY (id),
  CONSTRAINT discrepancies_oficio_id_fkey FOREIGN KEY (oficio_id) REFERENCES public.email_outbound(id),
  CONSTRAINT discrepancies_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT discrepancies_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT discrepancies_gesp_task_id_fkey FOREIGN KEY (gesp_task_id) REFERENCES public.gesp_tasks(id)
);
CREATE TABLE public.dou_alertas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  alvara_id uuid,
  publicacao_id uuid,
  company_id uuid,
  prospect_id uuid,
  cnpj text NOT NULL,
  razao_social text,
  tipo_alerta text NOT NULL DEFAULT 'novo_alvara'::text,
  titulo text NOT NULL,
  mensagem text NOT NULL,
  prioridade text DEFAULT 'normal'::text,
  status text DEFAULT 'pendente'::text,
  enviado_em timestamp with time zone,
  lido_em timestamp with time zone,
  canal text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dou_alertas_pkey PRIMARY KEY (id),
  CONSTRAINT dou_alertas_alvara_id_fkey FOREIGN KEY (alvara_id) REFERENCES public.dou_alvaras(id),
  CONSTRAINT dou_alertas_publicacao_id_fkey FOREIGN KEY (publicacao_id) REFERENCES public.dou_publicacoes(id)
);
CREATE TABLE public.dou_alvaras (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  publicacao_id uuid,
  razao_social text NOT NULL,
  cnpj text NOT NULL,
  cnpj_limpo text NOT NULL,
  uf text,
  municipio text,
  tipo_alvara text NOT NULL DEFAULT 'autorizacao'::text,
  subtipo text,
  numero_processo text,
  delegacia text,
  itens_liberados jsonb DEFAULT '[]'::jsonb,
  validade_dias integer,
  data_validade date,
  texto_original text NOT NULL,
  company_id uuid,
  prospect_id uuid,
  notificado boolean DEFAULT false,
  data_notificacao timestamp with time zone,
  canal_notificacao text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dou_alvaras_pkey PRIMARY KEY (id),
  CONSTRAINT dou_alvaras_publicacao_id_fkey FOREIGN KEY (publicacao_id) REFERENCES public.dou_publicacoes(id)
);
CREATE TABLE public.dou_publicacoes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  titulo text NOT NULL,
  tipo_ato text NOT NULL DEFAULT 'alvara'::text,
  numero_ato text,
  data_ato date,
  data_publicacao date NOT NULL,
  secao integer NOT NULL DEFAULT 1,
  edicao text,
  pagina text,
  orgao_principal text,
  orgao_subordinado text,
  unidade text,
  texto_completo text NOT NULL,
  resumo text,
  url_publicacao text,
  url_pdf text,
  slug text,
  dou_id text UNIQUE,
  assinante text,
  cargo_assinante text,
  processado boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dou_publicacoes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dou_scraper_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  data_alvo date NOT NULL,
  secao integer NOT NULL DEFAULT 1,
  status text DEFAULT 'running'::text,
  publicacoes_encontradas integer DEFAULT 0,
  alvaras_extraidos integer DEFAULT 0,
  alertas_gerados integer DEFAULT 0,
  empresas_vinculadas integer DEFAULT 0,
  erro text,
  detalhes jsonb,
  iniciado_em timestamp with time zone DEFAULT now(),
  finalizado_em timestamp with time zone,
  duracao_ms integer,
  CONSTRAINT dou_scraper_runs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.email_inbound (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  gmail_message_id text NOT NULL UNIQUE,
  from_email text NOT NULL,
  to_email text,
  subject text NOT NULL,
  body_text text NOT NULL,
  body_html text,
  attachments jsonb DEFAULT '[]'::jsonb,
  received_at timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'recebido'::text CHECK (status = ANY (ARRAY['recebido'::text, 'processado'::text, 'erro'::text])),
  parser_resultado jsonb,
  tipo_demanda text,
  confidence_score numeric,
  workflow_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  thread_id uuid,
  CONSTRAINT email_inbound_pkey PRIMARY KEY (id),
  CONSTRAINT email_inbound_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT email_inbound_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.email_threads(id)
);
CREATE TABLE public.email_outbound (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  template_id text NOT NULL CHECK (template_id = ANY (ARRAY['A'::text, 'B'::text, 'C'::text, 'D'::text, 'E'::text, 'F'::text, 'G'::text, 'OF-A'::text, 'OF-B'::text, 'OF-C'::text, 'OF-D'::text, 'OF-E'::text])),
  mode text NOT NULL CHECK (mode = ANY (ARRAY['CLIENTE_HTML'::text, 'OFICIO_PF'::text])),
  from_email text NOT NULL,
  to_email text NOT NULL,
  cc_email text,
  subject text NOT NULL,
  body_html text,
  body_text text,
  attachments jsonb DEFAULT '[]'::jsonb,
  resend_id text,
  status text NOT NULL DEFAULT 'pendente'::text CHECK (status = ANY (ARRAY['pendente'::text, 'enviado'::text, 'erro'::text])),
  erro_detalhe text,
  workflow_id uuid,
  gesp_task_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  sent_at timestamp with time zone,
  thread_id uuid,
  cc_emails ARRAY DEFAULT '{}'::text[],
  opened_at timestamp with time zone,
  clicked_at timestamp with time zone,
  CONSTRAINT email_outbound_pkey PRIMARY KEY (id),
  CONSTRAINT email_outbound_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT email_outbound_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.email_threads(id)
);
CREATE TABLE public.email_threads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid,
  subject text NOT NULL,
  cnpj_detectado text,
  status text NOT NULL DEFAULT 'PENDENTE'::text CHECK (status = ANY (ARRAY['PENDENTE'::text, 'EM_ANDAMENTO'::text, 'FINALIZADO'::text])),
  tipo_demanda text,
  last_message_id text,
  message_ids ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  finalizado_at timestamp with time zone,
  finalizado_por uuid,
  CONSTRAINT email_threads_pkey PRIMARY KEY (id),
  CONSTRAINT email_threads_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT email_threads_finalizado_por_fkey FOREIGN KEY (finalizado_por) REFERENCES public.users(id)
);
CREATE TABLE public.email_workflows (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  email_inbound_id uuid,
  tipo_demanda text NOT NULL,
  prioridade text NOT NULL DEFAULT 'normal'::text CHECK (prioridade = ANY (ARRAY['normal'::text, 'urgente'::text])),
  status text NOT NULL DEFAULT 'recebido'::text CHECK (status = ANY (ARRAY['recebido'::text, 'classificado'::text, 'aguardando_aprovacao'::text, 'aprovado'::text, 'executando'::text, 'concluido'::text, 'erro'::text, 'caso_desconhecido'::text])),
  dados_extraidos jsonb NOT NULL DEFAULT '{}'::jsonb,
  aprovado_por uuid,
  aprovado_em timestamp with time zone,
  gesp_task_ids ARRAY DEFAULT '{}'::uuid[],
  email_outbound_ids ARRAY DEFAULT '{}'::uuid[],
  erro_detalhe text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT email_workflows_pkey PRIMARY KEY (id),
  CONSTRAINT email_workflows_email_inbound_id_fkey FOREIGN KEY (email_inbound_id) REFERENCES public.email_inbound(id),
  CONSTRAINT email_workflows_aprovado_por_fkey FOREIGN KEY (aprovado_por) REFERENCES public.users(id),
  CONSTRAINT email_workflows_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.employees (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  nome_completo text NOT NULL,
  cpf text NOT NULL,
  rg text NOT NULL,
  rg_orgao_emissor text NOT NULL,
  rg_uf character NOT NULL,
  rg_data_emissao date,
  data_nascimento date NOT NULL,
  sexo character NOT NULL CHECK (sexo = ANY (ARRAY['M'::bpchar, 'F'::bpchar])),
  nacionalidade text DEFAULT 'Brasileira'::text,
  naturalidade text,
  nome_mae text NOT NULL,
  nome_pai text,
  estado_civil text,
  email text NOT NULL,
  telefone1 text NOT NULL,
  telefone2 text,
  cep text,
  logradouro text,
  numero text,
  complemento text,
  bairro text,
  cidade text,
  uf character,
  status text NOT NULL DEFAULT 'ativo'::text CHECK (status = ANY (ARRAY['ativo'::text, 'inativo'::text, 'afastado'::text, 'demitido'::text])),
  data_admissao date NOT NULL,
  data_desligamento date,
  tipo_vinculo text NOT NULL DEFAULT 'CLT'::text CHECK (tipo_vinculo = ANY (ARRAY['CLT'::text, 'Terceirizado'::text])),
  funcao_principal text NOT NULL CHECK (funcao_principal = ANY (ARRAY['Vigilante Patrimonial'::text, 'Vigilante Armado'::text, 'Vigilante Desarmado'::text, 'Vigilante de Transporte de Valores'::text, 'Vigilante de Escolta Armada'::text, 'Vigilante de Segurança Pessoal Privada'::text, 'Vigilante de Grandes Eventos'::text])),
  posto_designado uuid,
  cnv_numero text NOT NULL,
  cnv_uf_emissora character NOT NULL,
  cnv_data_emissao date NOT NULL,
  cnv_data_validade date NOT NULL,
  cnv_situacao text NOT NULL DEFAULT 'valida'::text CHECK (cnv_situacao = ANY (ARRAY['valida'::text, 'vencida'::text, 'suspensa'::text, 'cancelada'::text])),
  reciclagem_data_ultimo_curso date,
  reciclagem_data_validade date,
  reciclagem_escola text,
  reciclagem_municipio text,
  formacao_data date,
  formacao_escola text,
  formacao_municipio text,
  formacao_uf character,
  arma_numero_serie text,
  porte_arma_validade date,
  colete_numero_serie text,
  colete_data_validade date,
  crv text,
  laudo_medico boolean DEFAULT false,
  antecedentes_criminais boolean DEFAULT false,
  aptidao_porte_arma boolean DEFAULT false,
  tipo_arma_habilitada text,
  municipio_trabalho text,
  uf_trabalho character,
  alertas_ativos jsonb NOT NULL DEFAULT '{"cnv_data_validade": true, "porte_arma_validade": true, "colete_data_validade": true, "reciclagem_data_validade": true}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT employees_posto_designado_fkey FOREIGN KEY (posto_designado) REFERENCES public.job_posts(id)
);
CREATE TABLE public.gesp_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  process_code text NOT NULL,
  process_name text NOT NULL,
  agent_name text NOT NULL,
  agent_run_id text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  urgency USER-DEFINED NOT NULL DEFAULT 'normal'::gesp_approval_urgency,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::gesp_approval_status,
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  admin_notes text,
  decided_at timestamp with time zone,
  decided_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gesp_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT gesp_approvals_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT gesp_approvals_decided_by_fkey FOREIGN KEY (decided_by) REFERENCES public.users(id)
);
CREATE TABLE public.gesp_holidays (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  data date NOT NULL UNIQUE,
  descricao text NOT NULL,
  tipo text DEFAULT 'nacional'::text CHECK (tipo = ANY (ARRAY['nacional'::text, 'ponto_facultativo'::text])),
  CONSTRAINT gesp_holidays_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gesp_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  browser_pid integer,
  status text NOT NULL DEFAULT 'ativo'::text CHECK (status = ANY (ARRAY['ativo'::text, 'finalizado'::text, 'erro'::text])),
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  finished_at timestamp with time zone,
  erro_detalhe text,
  acoes_executadas integer DEFAULT 0,
  prints_capturados integer DEFAULT 0,
  tempo_total_ms integer,
  CONSTRAINT gesp_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT gesp_sessions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.gesp_snapshots (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  session_id uuid,
  snapshot_data jsonb NOT NULL,
  vigilantes_count integer DEFAULT 0,
  postos_count integer DEFAULT 0,
  armas_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gesp_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT gesp_snapshots_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT gesp_snapshots_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.gesp_sessions(id)
);
CREATE TABLE public.gesp_tasks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  session_id uuid,
  workflow_id uuid,
  tipo_acao text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pendente'::text CHECK (status = ANY (ARRAY['pendente'::text, 'executando'::text, 'concluido'::text, 'erro'::text, 'retry'::text])),
  tentativas integer NOT NULL DEFAULT 0,
  max_tentativas integer NOT NULL DEFAULT 5,
  print_antes_r2 text,
  print_depois_r2 text,
  print_erro_r2 text,
  protocolo_gesp text,
  erro_detalhe text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  executed_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT gesp_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT gesp_tasks_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT gesp_tasks_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.gesp_sessions(id),
  CONSTRAINT gesp_tasks_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES public.email_workflows(id)
);
CREATE TABLE public.iml_event_edges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_event_id uuid NOT NULL,
  target_event_id uuid NOT NULL,
  relation_type text NOT NULL CHECK (relation_type = ANY (ARRAY['CAUSOU'::text, 'PRECEDEU'::text, 'BLOQUEOU'::text, 'RESOLVEU'::text, 'ESCALOU'::text, 'REVERTEU'::text, 'COMPLEMENTOU'::text, 'SIMILAR'::text])),
  confidence double precision NOT NULL DEFAULT 1.0 CHECK (confidence >= 0::double precision AND confidence <= 1::double precision),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT iml_event_edges_pkey PRIMARY KEY (id),
  CONSTRAINT iml_event_edges_source_event_id_fkey FOREIGN KEY (source_event_id) REFERENCES public.iml_events(id),
  CONSTRAINT iml_event_edges_target_event_id_fkey FOREIGN KEY (target_event_id) REFERENCES public.iml_events(id)
);
CREATE TABLE public.iml_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['PUBLICACAO_DOU'::text, 'PROCESSO_GESP'::text, 'VENCIMENTO'::text, 'COMUNICACAO_CLIENTE'::text, 'DECISAO_AGENTE'::text, 'ESCALACAO_HUMANA'::text, 'COMPLIANCE_CHECK'::text, 'PROSPECT_QUALIFICADO'::text, 'WORKFLOW_INICIADO'::text, 'WORKFLOW_CONCLUIDO'::text, 'ERRO_SISTEMA'::text, 'INSIGHT_GERADO'::text, 'PLAYBOOK_AJUSTE'::text, 'ADMIN_ACAO'::text])),
  entity_type text NOT NULL CHECK (entity_type = ANY (ARRAY['company'::text, 'employee'::text, 'agent_run'::text, 'email'::text, 'gesp_task'::text, 'dou_item'::text, 'prospect'::text, 'workflow'::text, 'document'::text, 'system'::text])),
  entity_id text,
  agent_name text CHECK (agent_name = ANY (ARRAY['captador'::text, 'operacional'::text, 'comunicador'::text, 'orquestrador'::text])),
  agent_run_id uuid,
  company_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  severity text NOT NULL DEFAULT 'info'::text CHECK (severity = ANY (ARRAY['critical'::text, 'high'::text, 'medium'::text, 'low'::text, 'info'::text])),
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  search_text text DEFAULT ((((COALESCE((metadata ->> 'resumo'::text), ''::text) || ' '::text) || COALESCE((metadata ->> 'descricao'::text), ''::text)) || ' '::text) || COALESCE((metadata ->> 'razao_social'::text), ''::text)),
  CONSTRAINT iml_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.iml_insights (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  insight_type text NOT NULL CHECK (insight_type = ANY (ARRAY['TIMING_PATTERN'::text, 'PERFORMANCE_PATTERN'::text, 'BEHAVIORAL_PATTERN'::text, 'CORRELATION'::text, 'ANOMALY'::text, 'OPTIMIZATION'::text, 'RISK_SIGNAL'::text, 'RECOMMENDATION'::text])),
  title text NOT NULL,
  description text NOT NULL,
  suggested_action text,
  suggested_params jsonb DEFAULT '{}'::jsonb,
  evidence_count integer NOT NULL DEFAULT 0,
  evidence_event_ids ARRAY DEFAULT '{}'::uuid[],
  confidence double precision NOT NULL DEFAULT 0.0 CHECK (confidence >= 0::double precision AND confidence <= 1::double precision),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'ready'::text, 'admin_approved'::text, 'admin_rejected'::text, 'applied'::text, 'expired'::text, 'superseded'::text])),
  admin_approved boolean NOT NULL DEFAULT false,
  admin_approved_by uuid,
  admin_approved_at timestamp with time zone,
  admin_notes text,
  related_agent text CHECK (related_agent = ANY (ARRAY['captador'::text, 'operacional'::text, 'comunicador'::text, 'orquestrador'::text])),
  related_company_id uuid,
  impact_level text DEFAULT 'medium'::text CHECK (impact_level = ANY (ARRAY['critical'::text, 'high'::text, 'medium'::text, 'low'::text])),
  version integer NOT NULL DEFAULT 1,
  parent_insight_id uuid,
  first_detected_at timestamp with time zone NOT NULL DEFAULT now(),
  last_evidence_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT iml_insights_pkey PRIMARY KEY (id),
  CONSTRAINT iml_insights_parent_insight_id_fkey FOREIGN KEY (parent_insight_id) REFERENCES public.iml_insights(id)
);
CREATE TABLE public.iml_playbook_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  playbook_rule_id uuid NOT NULL,
  agent_run_id uuid,
  rule_code text NOT NULL,
  param_name text NOT NULL,
  original_value jsonb NOT NULL,
  applied_value jsonb NOT NULL,
  apply_context jsonb NOT NULL DEFAULT '{}'::jsonb,
  outcome text CHECK (outcome = ANY (ARRAY['success'::text, 'neutral'::text, 'negative'::text, 'unknown'::text])),
  outcome_details jsonb,
  applied_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT iml_playbook_log_pkey PRIMARY KEY (id),
  CONSTRAINT iml_playbook_log_playbook_rule_id_fkey FOREIGN KEY (playbook_rule_id) REFERENCES public.iml_playbook_rules(id)
);
CREATE TABLE public.iml_playbook_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rule_code text NOT NULL CHECK (rule_code ~ '^R[0-9]{1,2}$'::text),
  param_name text NOT NULL,
  default_value jsonb NOT NULL,
  adjusted_value jsonb NOT NULL,
  apply_context jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_insight_id uuid,
  active boolean NOT NULL DEFAULT false,
  approved_by uuid,
  approved_at timestamp with time zone,
  times_applied integer NOT NULL DEFAULT 0,
  last_applied_at timestamp with time zone,
  effectiveness_score double precision,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT iml_playbook_rules_pkey PRIMARY KEY (id),
  CONSTRAINT iml_playbook_rules_source_insight_id_fkey FOREIGN KEY (source_insight_id) REFERENCES public.iml_insights(id)
);
CREATE TABLE public.job_posts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  nome text NOT NULL,
  endereco text NOT NULL,
  cidade text NOT NULL,
  uf character NOT NULL,
  cep text,
  status text NOT NULL DEFAULT 'ativo'::text CHECK (status = ANY (ARRAY['ativo'::text, 'encerrado'::text, 'pendente'::text])),
  data_abertura date,
  data_encerramento date,
  gesp_protocolo text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_posts_pkey PRIMARY KEY (id),
  CONSTRAINT job_posts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.knowledge_base (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email_original_id uuid,
  descricao_caso text NOT NULL,
  solucao_adotada text,
  resolvido_por_id uuid,
  tempo_resolucao_min integer,
  status text NOT NULL DEFAULT 'pendente'::text CHECK (status = ANY (ARRAY['pendente'::text, 'aprovado'::text, 'rejeitado'::text, 'auto_aprovado'::text])),
  confianca_ia numeric DEFAULT 0.00,
  aprovado_por_email boolean DEFAULT false,
  tags ARRAY DEFAULT '{}'::text[],
  kb_ref text UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_base_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_base_email_original_id_fkey FOREIGN KEY (email_original_id) REFERENCES public.email_inbound(id),
  CONSTRAINT knowledge_base_resolvido_por_id_fkey FOREIGN KEY (resolvido_por_id) REFERENCES public.users(id)
);
CREATE TABLE public.parser_keywords (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tipo_demanda text NOT NULL,
  keywords ARRAY NOT NULL,
  acao_automatica text NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT parser_keywords_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pf_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  tipo_oficio text NOT NULL CHECK (tipo_oficio = ANY (ARRAY['OF-A'::text, 'OF-B'::text, 'OF-C'::text, 'OF-D'::text, 'OF-E'::text])),
  delesp_uf character NOT NULL,
  delesp_email text NOT NULL,
  assunto text NOT NULL,
  corpo_texto text NOT NULL,
  attachments_r2 ARRAY DEFAULT '{}'::text[],
  workflow_id uuid,
  email_outbound_id uuid,
  status text NOT NULL DEFAULT 'rascunho'::text CHECK (status = ANY (ARRAY['rascunho'::text, 'enviado'::text, 'confirmado'::text, 'respondido'::text])),
  protocolo text,
  resposta_pf text,
  respondido_em timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  sent_at timestamp with time zone,
  CONSTRAINT pf_requests_pkey PRIMARY KEY (id),
  CONSTRAINT pf_requests_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT pf_requests_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES public.email_workflows(id),
  CONSTRAINT pf_requests_email_outbound_id_fkey FOREIGN KEY (email_outbound_id) REFERENCES public.email_outbound(id)
);
CREATE TABLE public.procuracoes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  cpf_procurador character varying NOT NULL,
  nome_procurador text NOT NULL,
  poderes text NOT NULL DEFAULT 'plenos'::text CHECK (poderes = ANY (ARRAY['plenos'::text, 'limitados'::text])),
  poderes_descricao text,
  status text NOT NULL DEFAULT 'pendente'::text CHECK (status = ANY (ARRAY['pendente'::text, 'instrucoes_enviadas'::text, 'cliente_confirmou'::text, 'validada'::text, 'rejeitada'::text, 'revogada'::text, 'expirada'::text])),
  instrucoes_enviadas_at timestamp with time zone,
  cliente_confirmou_at timestamp with time zone,
  validada_at timestamp with time zone,
  validada_por uuid,
  rejeitada_at timestamp with time zone,
  motivo_rejeicao text,
  revogada_at timestamp with time zone,
  comprovante_r2_path text,
  prazo_limite date,
  lembrete_enviado boolean DEFAULT false,
  observacoes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT procuracoes_pkey PRIMARY KEY (id),
  CONSTRAINT procuracoes_validada_por_fkey FOREIGN KEY (validada_por) REFERENCES public.users(id),
  CONSTRAINT procuracoes_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.prospect_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prospect_id uuid NOT NULL,
  user_id uuid NOT NULL,
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['ligacao'::character varying, 'email'::character varying, 'reuniao'::character varying, 'whatsapp'::character varying, 'nota'::character varying, 'proposta'::character varying, 'followup'::character varying]::text[])),
  descricao text NOT NULL,
  resultado text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT prospect_activities_pkey PRIMARY KEY (id),
  CONSTRAINT prospect_activities_prospect_id_fkey FOREIGN KEY (prospect_id) REFERENCES public.prospects(id)
);
CREATE TABLE public.prospects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cnpj character varying NOT NULL UNIQUE,
  razao_social text NOT NULL,
  nome_fantasia text,
  cnae_principal character varying,
  cnae_descricao text,
  data_abertura character varying,
  capital_social numeric,
  porte text,
  logradouro text,
  numero character varying,
  complemento text,
  bairro text,
  cep character varying,
  municipio text,
  uf character varying,
  telefone1 character varying,
  telefone2 character varying,
  email text,
  status character varying NOT NULL DEFAULT 'novo'::character varying CHECK (status::text = ANY (ARRAY['novo'::character varying, 'contatado'::character varying, 'qualificado'::character varying, 'proposta_enviada'::character varying, 'negociacao'::character varying, 'ganho'::character varying, 'perdido'::character varying]::text[])),
  source character varying NOT NULL DEFAULT 'csv_rfb'::character varying CHECK (source::text = ANY (ARRAY['csv_rfb'::character varying, 'dou'::character varying, 'website'::character varying, 'indicacao'::character varying, 'outbound'::character varying, 'evento'::character varying, 'outro'::character varying]::text[])),
  segmento character varying CHECK (segmento IS NULL OR (segmento::text = ANY (ARRAY['micro'::character varying, 'pequena'::character varying, 'media'::character varying, 'grande'::character varying]::text[]))),
  temperatura character varying NOT NULL DEFAULT 'frio'::character varying CHECK (temperatura::text = ANY (ARRAY['frio'::character varying, 'morno'::character varying, 'quente'::character varying]::text[])),
  score integer NOT NULL DEFAULT 0 CHECK (score >= 0 AND score <= 100),
  contato_nome text,
  contato_cargo text,
  contato_telefone character varying,
  contato_email text,
  plano_interesse character varying,
  valor_estimado numeric,
  motivo_perda text,
  ultimo_contato timestamp with time zone,
  proximo_followup date,
  data_conversao timestamp with time zone,
  company_id uuid,
  notas text,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  importado_por text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT prospects_pkey PRIMARY KEY (id),
  CONSTRAINT prospects_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.refresh_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  token_hash text NOT NULL UNIQUE,
  family_id text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  used boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.settings (
  key text NOT NULL,
  value jsonb NOT NULL,
  description text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  CONSTRAINT settings_pkey PRIMARY KEY (key),
  CONSTRAINT settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.system_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tipo text NOT NULL,
  severidade text NOT NULL DEFAULT 'info'::text CHECK (severidade = ANY (ARRAY['info'::text, 'warning'::text, 'error'::text, 'critical'::text])),
  mensagem text NOT NULL,
  detalhes jsonb DEFAULT '{}'::jsonb,
  company_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT system_events_pkey PRIMARY KEY (id),
  CONSTRAINT system_events_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.system_health (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  component text NOT NULL,
  status text NOT NULL DEFAULT 'healthy'::text CHECK (status = ANY (ARRAY['healthy'::text, 'degraded'::text, 'unhealthy'::text, 'offline'::text])),
  last_heartbeat timestamp with time zone NOT NULL DEFAULT now(),
  details jsonb DEFAULT '{}'::jsonb,
  error_count integer DEFAULT 0,
  uptime_seconds integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT system_health_pkey PRIMARY KEY (id)
);
CREATE TABLE public.thread_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  thread_id uuid NOT NULL,
  user_id uuid,
  email text NOT NULL,
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['interno_admin'::text, 'interno_operador'::text, 'externo_cnpj'::text, 'externo_outro'::text])),
  motivo_entrada text NOT NULL CHECK (motivo_entrada = ANY (ARRAY['responsavel_empresa'::text, 'interveio'::text, 'cliente_copiou'::text, 'admin_manual'::text])),
  entrou_em timestamp with time zone NOT NULL DEFAULT now(),
  ativo boolean NOT NULL DEFAULT true,
  CONSTRAINT thread_participants_pkey PRIMARY KEY (id),
  CONSTRAINT thread_participants_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.email_threads(id),
  CONSTRAINT thread_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  thread_id uuid,
  company_id uuid,
  t_primeira_leitura timestamp with time zone,
  t_acao_iniciada timestamp with time zone,
  t_cliente_atualizado timestamp with time zone,
  minutos_resposta integer,
  minutos_execucao integer,
  dentro_do_prazo boolean,
  modulo_gesp text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT user_metrics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_metrics_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.email_threads(id),
  CONSTRAINT user_metrics_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  nome text NOT NULL,
  role text NOT NULL DEFAULT 'viewer'::text CHECK (role = ANY (ARRAY['admin'::text, 'operador'::text, 'viewer'::text])),
  company_ids ARRAY DEFAULT '{}'::uuid[],
  deve_trocar_senha boolean NOT NULL DEFAULT true,
  tentativas_falhas integer NOT NULL DEFAULT 0,
  bloqueado_ate timestamp with time zone,
  mfa_enabled boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vehicle_maintenance (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vehicle_id uuid NOT NULL,
  company_id uuid NOT NULL,
  tipo text NOT NULL,
  descricao text,
  km_na_manutencao numeric,
  valor numeric,
  nota_fiscal text,
  nf_r2_path text,
  oficina text,
  proxima_km numeric,
  proxima_data date,
  realizada_em date NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vehicle_maintenance_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_maintenance_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id),
  CONSTRAINT vehicle_maintenance_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.vehicle_telemetry (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vehicle_id uuid NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  velocidade numeric,
  ignicao boolean,
  odometro numeric,
  provider text,
  raw_data jsonb,
  recorded_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vehicle_telemetry_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_telemetry_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id)
);
CREATE TABLE public.vehicles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  placa text NOT NULL,
  modelo text NOT NULL,
  marca text,
  ano integer,
  cor text,
  tipo text NOT NULL DEFAULT 'operacional'::text CHECK (tipo = ANY (ARRAY['operacional'::text, 'escolta'::text, 'transporte_valores'::text, 'administrativo'::text])),
  chassi text,
  renavam text,
  km_atual numeric NOT NULL DEFAULT 0,
  gps_provider text,
  gps_device_id text,
  gps_ultimo_lat numeric,
  gps_ultimo_lng numeric,
  gps_ultima_leitura timestamp with time zone,
  licenciamento_validade date,
  seguro_validade date,
  seguro_apolice text,
  vistoria_pf_validade date,
  ultima_troca_oleo_km numeric,
  ultima_troca_pneu_km numeric,
  ultima_pastilha_km numeric,
  ultima_correia_km numeric,
  ultima_revisao_km numeric,
  data_bateria date,
  alertas_ativos jsonb NOT NULL DEFAULT '{"bateria": true, "troca_oleo": true, "troca_pneu": true, "revisao_geral": true, "pastilha_freio": true, "correia_dentada": true, "seguro_validade": true, "vistoria_pf_validade": true, "licenciamento_validade": true}'::jsonb,
  status text NOT NULL DEFAULT 'ativo'::text CHECK (status = ANY (ARRAY['ativo'::text, 'inativo'::text, 'manutencao'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vehicles_pkey PRIMARY KEY (id),
  CONSTRAINT vehicles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.vests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  numero_serie text NOT NULL,
  nivel_protecao text NOT NULL,
  fabricante text,
  data_fabricacao date,
  data_validade date NOT NULL,
  status text NOT NULL DEFAULT 'ativo'::text CHECK (status = ANY (ARRAY['ativo'::text, 'baixa_validade'::text, 'baixa_defeito'::text])),
  baixa_comprovante_r2 text,
  baixa_data date,
  employee_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vests_pkey PRIMARY KEY (id),
  CONSTRAINT vests_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT vests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.weapons (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  tipo text NOT NULL,
  marca text,
  modelo text,
  calibre text NOT NULL,
  numero_serie text NOT NULL,
  registro_sinarm text,
  status text NOT NULL DEFAULT 'ativo'::text CHECK (status = ANY (ARRAY['ativo'::text, 'vendida'::text, 'baixa'::text, 'transporte'::text])),
  evento_tipo text CHECK (evento_tipo = ANY (ARRAY['compra'::text, 'venda'::text, 'transporte'::text, 'baixa'::text])),
  evento_data date,
  evento_contraparte text,
  evento_nf text,
  evento_nf_r2_path text,
  employee_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT weapons_pkey PRIMARY KEY (id),
  CONSTRAINT weapons_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT weapons_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.webhook_processed (
  svix_id text NOT NULL,
  endpoint text NOT NULL,
  processed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT webhook_processed_pkey PRIMARY KEY (svix_id)
);
CREATE TABLE public.workflow_email_outbound (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workflow_id uuid NOT NULL,
  email_outbound_id uuid NOT NULL,
  added_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT workflow_email_outbound_pkey PRIMARY KEY (id),
  CONSTRAINT workflow_email_outbound_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES public.email_workflows(id),
  CONSTRAINT workflow_email_outbound_email_outbound_id_fkey FOREIGN KEY (email_outbound_id) REFERENCES public.email_outbound(id)
);
CREATE TABLE public.workflow_gesp_tasks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workflow_id uuid NOT NULL,
  gesp_task_id uuid NOT NULL,
  added_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT workflow_gesp_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT workflow_gesp_tasks_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES public.email_workflows(id),
  CONSTRAINT workflow_gesp_tasks_gesp_task_id_fkey FOREIGN KEY (gesp_task_id) REFERENCES public.gesp_tasks(id)
);